/**
 * Seed Data - Missions and Achievements
 */

import { MissionType } from '@prisma/client';

export const demoMissions = [
  {
    title: 'Ice Breaker: Your Perfect Day',
    description: 'Describe your ideal perfect day from morning to night. What would you do?',
    missionType: MissionType.ICE_BREAKER,
    difficulty: 1,
    xpReward: 10,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Daily Challenge: Morning Routine',
    description: 'Share your morning routine! How do you start your day?',
    missionType: MissionType.DAILY,
    difficulty: 1,
    xpReward: 15,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Weekly Quest: Hidden Talent',
    description: "Show us a talent that most people don't know you have!",
    missionType: MissionType.WEEKLY,
    difficulty: 2,
    xpReward: 25,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Favorite Travel Memory',
    description: 'Share your favorite travel memory. Where was it and why was it special?',
    missionType: MissionType.ICE_BREAKER,
    difficulty: 1,
    xpReward: 10,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Cook Something New',
    description: 'Try cooking a dish from a cuisine you\'ve never tried before and share the result!',
    missionType: MissionType.WEEKLY,
    difficulty: 3,
    xpReward: 30,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Sunset Photo',
    description: 'Capture a beautiful sunset and share it with the community.',
    missionType: MissionType.DAILY,
    difficulty: 1,
    xpReward: 15,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Special: Valentine\'s Day',
    description: 'What does love mean to you? Share your thoughts in a creative way.',
    missionType: MissionType.SPECIAL,
    difficulty: 2,
    xpReward: 50,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Draw Your Mood',
    description: 'Draw or sketch how you feel today. Let your creativity flow!',
    missionType: MissionType.DAILY,
    difficulty: 1,
    xpReward: 15,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Two Truths and a Lie',
    description: 'Share two truths and one lie about yourself. Let others guess!',
    missionType: MissionType.ICE_BREAKER,
    difficulty: 1,
    xpReward: 10,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Weekly: Bucket List',
    description: 'Share the top 3 things on your bucket list and why.',
    missionType: MissionType.WEEKLY,
    difficulty: 2,
    xpReward: 25,
    activeFrom: new Date(),
    activeUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
  // Additional missions (11-25)
  { title: 'Send a Voice Message', description: 'Record and send your first voice message to someone!', missionType: MissionType.DAILY, difficulty: 1, xpReward: 20, activeFrom: new Date(), activeUntil: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000) },
  { title: 'Complete Your Bio', description: 'Fill out your complete profile bio and personality section', missionType: MissionType.ICE_BREAKER, difficulty: 1, xpReward: 30, activeFrom: new Date(), activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000) },
  { title: 'Like 3 Profiles', description: 'Show some love! Like at least 3 profiles today', missionType: MissionType.DAILY, difficulty: 1, xpReward: 15, activeFrom: new Date(), activeUntil: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000) },
  { title: 'Start 5 Conversations', description: 'Be social! Start conversations with 5 different people', missionType: MissionType.WEEKLY, difficulty: 2, xpReward: 40, activeFrom: new Date(), activeUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) },
  { title: 'Complete Compatibility Quiz', description: 'Take the compatibility quiz to improve your matches!', missionType: MissionType.ICE_BREAKER, difficulty: 2, xpReward: 35, activeFrom: new Date(), activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000) },
  { title: 'Share a Story', description: 'Post your first story and let others see your day!', missionType: MissionType.DAILY, difficulty: 1, xpReward: 20, activeFrom: new Date(), activeUntil: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000) },
  { title: 'First Match', description: 'Get your first mutual match!', missionType: MissionType.SPECIAL, difficulty: 2, xpReward: 100, activeFrom: new Date(), activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000) },
  { title: 'Premium Member Welcome', description: 'Upgrade to premium and unlock exclusive features!', missionType: MissionType.SPECIAL, difficulty: 1, xpReward: 50, activeFrom: new Date(), activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000) },
  { title: 'Invite a Friend', description: 'Refer a friend to join Bellor using your referral code', missionType: MissionType.SPECIAL, difficulty: 2, xpReward: 75, activeFrom: new Date(), activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000) },
  { title: 'Coffee Date Plan', description: 'Plan a virtual or real coffee date with a match', missionType: MissionType.WEEKLY, difficulty: 3, xpReward: 60, activeFrom: new Date(), activeUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) },
  { title: 'Favorite Music Genre', description: 'Share what music you love and why it speaks to you', missionType: MissionType.ICE_BREAKER, difficulty: 1, xpReward: 10, activeFrom: new Date(), activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000) },
  { title: 'Dream Vacation', description: 'Describe your dream vacation destination in detail', missionType: MissionType.ICE_BREAKER, difficulty: 1, xpReward: 10, activeFrom: new Date(), activeUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000) },
  { title: 'Weekend Plans', description: 'Share what you have planned for this weekend!', missionType: MissionType.WEEKLY, difficulty: 1, xpReward: 20, activeFrom: new Date(), activeUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) },
  { title: 'Pet Lover', description: 'Share a photo or story about your pet (or dream pet!)', missionType: MissionType.DAILY, difficulty: 1, xpReward: 15, activeFrom: new Date(), activeUntil: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000) },
  { title: 'Fitness Journey', description: 'Share your fitness goals or achievements this month', missionType: MissionType.WEEKLY, difficulty: 2, xpReward: 30, activeFrom: new Date(), activeUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) },
];

export const demoAchievements = [
  { name: 'First Response', description: 'Complete your first mission response', requirement: { type: 'response_count', value: 1 }, xpReward: 50, iconUrl: '🎯' },
  { name: 'Chatty', description: 'Start 5 conversations', requirement: { type: 'chat_count', value: 5 }, xpReward: 100, iconUrl: '💬' },
  { name: 'Social Butterfly', description: 'Complete 10 missions', requirement: { type: 'mission_count', value: 10 }, xpReward: 150, iconUrl: '🦋' },
  { name: 'Story Teller', description: 'Post your first story', requirement: { type: 'story_count', value: 1 }, xpReward: 75, iconUrl: '📖' },
  { name: 'Explorer', description: 'View 20 different profiles', requirement: { type: 'profile_views', value: 20 }, xpReward: 80, iconUrl: '🔍' },
  { name: 'Popular', description: 'Get 50 likes on your responses', requirement: { type: 'total_likes', value: 50 }, xpReward: 200, iconUrl: '⭐' },
  { name: 'Consistent', description: 'Complete 7 daily missions in a row', requirement: { type: 'streak', value: 7 }, xpReward: 250, iconUrl: '🔥' },
  { name: 'Premium Member', description: 'Upgrade to Premium', requirement: { type: 'premium', value: 1 }, xpReward: 100, iconUrl: '💎' },
  { name: 'Artist', description: 'Submit 5 drawing responses', requirement: { type: 'drawing_count', value: 5 }, xpReward: 120, iconUrl: '🎨' },
  { name: 'Connector', description: 'Match with 3 people', requirement: { type: 'match_count', value: 3 }, xpReward: 150, iconUrl: '🤝' },
  { name: 'Heart Breaker', description: 'Receive 100 likes', requirement: { type: 'received_likes', value: 100 }, xpReward: 300, iconUrl: '💘' },
  // Additional achievements (12-20)
  { name: 'Influencer', description: 'Get 500 followers', requirement: { type: 'followers', value: 500 }, xpReward: 400, iconUrl: '👑' },
  { name: 'Daily Streak Master', description: 'Complete daily missions for 30 days straight', requirement: { type: 'streak', value: 30 }, xpReward: 500, iconUrl: '⚡' },
  { name: 'Mission Master', description: 'Complete 50 total missions', requirement: { type: 'mission_count', value: 50 }, xpReward: 300, iconUrl: '🏆' },
  { name: 'Supporter', description: 'Maintain premium membership for 6 months', requirement: { type: 'premium_duration', value: 180 }, xpReward: 250, iconUrl: '⭐' },
  { name: '100 Likes', description: 'Give 100 likes to others', requirement: { type: 'given_likes', value: 100 }, xpReward: 150, iconUrl: '❤️' },
  { name: '50 Matches', description: 'Match with 50 people', requirement: { type: 'match_count', value: 50 }, xpReward: 400, iconUrl: '🎉' },
  { name: '1 Year Member', description: 'Be a Bellor member for 1 year', requirement: { type: 'member_duration', value: 365 }, xpReward: 600, iconUrl: '🎂' },
  { name: 'Voice Expert', description: 'Send 25 voice messages', requirement: { type: 'voice_count', value: 25 }, xpReward: 180, iconUrl: '🎤' },
  { name: 'Video Star', description: 'Send 10 video messages', requirement: { type: 'video_count', value: 10 }, xpReward: 200, iconUrl: '🎬' },
];
