/**
 * Seed Data - User Definitions (Part 3)
 * Additional 32 demo users for comprehensive testing
 * Includes Hebrew speakers, premium users, and varied characteristics
 */

import { Gender, Language } from '@prisma/client';

/**
 * Helper to create dates spread over 90 days
 */
function getRandomPastDate(daysAgo: number, variance: number = 10): Date {
  const days = daysAgo + Math.random() * variance;
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000);
}

/** Third batch of demo users - Hebrew speakers */
export const hebrewUsers = [
  {
    id: 'demo-user-hebrew-1',
    email: 'yael.israeli@example.com',
    firstName: 'Yael',
    lastName: 'Israeli',
    nickname: 'Yaeli',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'אוהבת לטייל, לקרוא ספרים ולהכיר אנשים חדשים. תמיד עם חיוך!',
    interests: ['טיולים', 'קריאה', 'בישול', 'יוגה'],
    birthDate: new Date('1997-04-12'),
    lookingFor: [Gender.MALE],
    profileImages: ['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400'],
    createdAt: getRandomPastDate(80, 10),
    isPremium: true,
  },
  {
    id: 'demo-user-hebrew-2',
    email: 'omer.cohen@example.com',
    firstName: 'Omer',
    lastName: 'Cohen',
    gender: Gender.MALE,
    preferredLanguage: Language.HEBREW,
    bio: 'מהנדס תוכנה שאוהב ספורט וטכנולוגיה. מחפש את האחת',
    interests: ['כדורגל', 'טכנולוגיה', 'נסיעות', 'מוזיקה'],
    birthDate: new Date('1994-08-20'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400'],
    createdAt: getRandomPastDate(70, 10),
  },
  {
    id: 'demo-user-hebrew-3',
    email: 'noa.levi@test.com',
    firstName: 'Noa',
    lastName: 'Levi',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'אמנית וצלמת עצמאית. חיים זה אומנות!',
    interests: ['צילום', 'ציור', 'תיאטרון', 'קפה'],
    birthDate: new Date('1998-11-05'),
    lookingFor: [Gender.MALE, Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400'],
    createdAt: getRandomPastDate(60, 10),
    isPremium: true,
  },
  {
    id: 'demo-user-hebrew-4',
    email: 'roi.mizrahi@example.com',
    firstName: 'Roi',
    lastName: 'Mizrahi',
    gender: Gender.MALE,
    preferredLanguage: Language.HEBREW,
    bio: 'עורך דין צעיר, אוהב לצאת ולבלות עם חברים',
    interests: ['משפטים', 'ספורט', 'מסעדות', 'חיי לילה'],
    birthDate: new Date('1995-02-14'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400'],
    createdAt: getRandomPastDate(50, 10),
  },
  {
    id: 'demo-user-hebrew-5',
    email: 'tamar.avraham@test.com',
    firstName: 'Tamar',
    lastName: 'Avraham',
    nickname: 'Tami',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'מורה לספורט ואוהבת חיים בריאים. הכל אפשרי!',
    interests: ['ספורט', 'תזונה', 'מדיטציה', 'טבע'],
    birthDate: new Date('1996-07-30'),
    lookingFor: [Gender.MALE],
    profileImages: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400'],
    createdAt: getRandomPastDate(40, 10),
    isPremium: true,
  },
];

/** English-speaking users */
export const englishUsers = [
  {
    id: 'demo-user-en-1',
    email: 'emma.johnson@example.com',
    firstName: 'Emma',
    lastName: 'Johnson',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Marketing professional who loves traveling and meeting new people',
    birthDate: new Date('1997-05-18'),
    lookingFor: [Gender.MALE],
    profileImages: ['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400'],
    createdAt: getRandomPastDate(75, 10),
  },
  {
    id: 'demo-user-en-2',
    email: 'michael.brown@test.com',
    firstName: 'Michael',
    lastName: 'Brown',
    nickname: 'Mike',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Entrepreneur and fitness enthusiast. Let\'s build something great!',
    birthDate: new Date('1993-09-25'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400'],
    createdAt: getRandomPastDate(65, 10),
    isPremium: true,
  },
  {
    id: 'demo-user-en-3',
    email: 'sophie.martinez@example.com',
    firstName: 'Sophie',
    lastName: 'Martinez',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Chef and food blogger. Life is too short for bad food!',
    birthDate: new Date('1998-12-08'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(55, 10),
  },
  {
    id: 'demo-user-en-4',
    email: 'alex.wilson@test.com',
    firstName: 'Alex',
    lastName: 'Wilson',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Graphic designer with a passion for creativity and innovation',
    birthDate: new Date('1996-03-17'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400'],
    createdAt: getRandomPastDate(45, 10),
  },
  {
    id: 'demo-user-en-5',
    email: 'olivia.taylor@example.com',
    firstName: 'Olivia',
    lastName: 'Taylor',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Doctor dedicated to helping others. Love nature and quiet moments',
    birthDate: new Date('1994-06-22'),
    lookingFor: [Gender.MALE],
    profileImages: ['https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400'],
    createdAt: getRandomPastDate(35, 10),
    isPremium: true,
  },
];

/** Mixed/bilingual users */
export const mixedUsers = [
  {
    id: 'demo-user-mixed-1',
    email: 'daniel.shapira@example.com',
    firstName: 'Daniel',
    lastName: 'Shapira',
    nickname: 'Dan',
    gender: Gender.MALE,
    preferredLanguage: Language.HEBREW,
    bio: 'International consultant, fluent in English and Hebrew. Love global cultures!',
    interests: ['Travel', 'Languages', 'Culture', 'Food'],
    birthDate: new Date('1995-10-11'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400'],
    createdAt: getRandomPastDate(30, 10),
    isPremium: true,
  },
  {
    id: 'demo-user-mixed-2',
    email: 'rachel.green@test.com',
    firstName: 'Rachel',
    lastName: 'Green',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Writer and traveler. Lived in both US and Israel. Love storytelling!',
    birthDate: new Date('1997-01-28'),
    lookingFor: [Gender.MALE],
    profileImages: ['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400'],
    createdAt: getRandomPastDate(25, 10),
  },
  {
    id: 'demo-user-mixed-3',
    email: 'yonatan.smith@example.com',
    firstName: 'Yonatan',
    lastName: 'Smith',
    gender: Gender.MALE,
    preferredLanguage: Language.HEBREW,
    bio: 'Software architect working remotely. Dual citizen, dual culture!',
    interests: ['Coding', 'Gaming', 'Travel', 'Music'],
    birthDate: new Date('1996-08-15'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(20, 10),
  },
];

/** Additional diverse users to reach 32 total */
export const additionalUsers = [
  {
    id: 'demo-user-add-1',
    email: 'jessica.white@example.com',
    firstName: 'Jessica',
    lastName: 'White',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Yoga instructor seeking balance and meaningful connections',
    birthDate: new Date('1998-04-09'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(85, 5),
  },
  {
    id: 'demo-user-add-2',
    email: 'adam.goldberg@test.com',
    firstName: 'Adam',
    lastName: 'Goldberg',
    gender: Gender.MALE,
    preferredLanguage: Language.HEBREW,
    bio: 'מוזיקאי עצמאי. החיים זה מנגינה!',
    birthDate: new Date('1994-11-23'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(72, 5),
    isPremium: true,
  },
  {
    id: 'demo-user-add-3',
    email: 'lily.chen@example.com',
    firstName: 'Lily',
    lastName: 'Chen',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    birthDate: new Date('1999-02-14'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(63, 5),
  },
  {
    id: 'demo-user-add-4',
    email: 'ben.katz@test.com',
    firstName: 'Ben',
    lastName: 'Katz',
    gender: Gender.MALE,
    preferredLanguage: Language.HEBREW,
    bio: 'חובב טבע ואוהב בעלי חיים',
    birthDate: new Date('1995-07-07'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(54, 5),
  },
  {
    id: 'demo-user-add-5',
    email: 'maya.patel@example.com',
    firstName: 'Maya',
    lastName: 'Patel',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Data scientist with a creative side',
    birthDate: new Date('1997-09-30'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(48, 5),
  },
  {
    id: 'demo-user-add-6',
    email: 'ethan.ross@test.com',
    firstName: 'Ethan',
    lastName: 'Ross',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Photographer capturing life\'s beautiful moments',
    birthDate: new Date('1996-12-19'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(42, 5),
    isPremium: true,
  },
  {
    id: 'demo-user-add-7',
    email: 'shani.davidov@example.com',
    firstName: 'Shani',
    lastName: 'Davidov',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'אדריכלית צעירה עם חזון',
    birthDate: new Date('1998-05-26'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(36, 5),
  },
  {
    id: 'demo-user-add-8',
    email: 'james.miller@test.com',
    firstName: 'James',
    lastName: 'Miller',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Entrepreneur building the future',
    birthDate: new Date('1993-03-08'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(28, 5),
  },
  {
    id: 'demo-user-add-9',
    email: 'natalie.berg@example.com',
    firstName: 'Natalie',
    lastName: 'Berg',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'מעצבת אופנה עם סטייל ייחודי',
    birthDate: new Date('1997-08-14'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(22, 5),
  },
  {
    id: 'demo-user-add-10',
    email: 'lucas.anderson@test.com',
    firstName: 'Lucas',
    lastName: 'Anderson',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Personal trainer helping people achieve their goals',
    birthDate: new Date('1995-11-02'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(18, 5),
  },
  {
    id: 'demo-user-add-11',
    email: 'maya.israeli@example.com',
    firstName: 'Maya',
    lastName: 'Israeli',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'סטודנטית לפסיכולוגיה ואוהבת אנשים',
    birthDate: new Date('1999-06-18'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(15, 5),
  },
  {
    id: 'demo-user-add-12',
    email: 'nathan.davis@test.com',
    firstName: 'Nathan',
    lastName: 'Davis',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Chef exploring culinary arts',
    birthDate: new Date('1994-01-21'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(12, 5),
  },
  {
    id: 'demo-user-add-13',
    email: 'hila.cohen@example.com',
    firstName: 'Hila',
    lastName: 'Cohen',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'עיתונאית חוקרת האמת',
    birthDate: new Date('1996-10-05'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(9, 5),
  },
  {
    id: 'demo-user-add-14',
    email: 'ryan.thompson@test.com',
    firstName: 'Ryan',
    lastName: 'Thompson',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Financial analyst with big dreams',
    birthDate: new Date('1993-07-12'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(6, 3),
  },
  {
    id: 'demo-user-add-15',
    email: 'avigail.russo@example.com',
    firstName: 'Avigail',
    lastName: 'Russo',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'רקדנית מקצועית שאוהבת לזוז',
    birthDate: new Date('1998-03-29'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(4, 2),
  },
  {
    id: 'demo-user-add-16',
    email: 'chris.lee@test.com',
    firstName: 'Chris',
    lastName: 'Lee',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Product manager shaping the future',
    birthDate: new Date('1995-09-16'),
    lookingFor: [Gender.FEMALE],
    createdAt: getRandomPastDate(2, 1),
  },
  {
    id: 'demo-user-add-17',
    email: 'maya.rosen@example.com',
    firstName: 'Maya',
    lastName: 'Rosen',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'מדריכת טיולים שמכירה את הארץ',
    birthDate: new Date('1997-12-24'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(1, 0),
  },
  {
    id: 'demo-user-add-18',
    email: 'noah.black@test.com',
    firstName: 'Noah',
    lastName: 'Black',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Artist and dreamer',
    birthDate: new Date('1996-05-03'),
    lookingFor: [Gender.FEMALE, Gender.MALE],
    createdAt: getRandomPastDate(1, 0),
  },
  {
    id: 'demo-user-add-19',
    email: 'shira.gold@example.com',
    firstName: 'Shira',
    lastName: 'Gold',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'מפתחת אפליקציות בסטארט-אפ',
    birthDate: new Date('1998-08-11'),
    lookingFor: [Gender.MALE],
    createdAt: getRandomPastDate(1, 0),
    isPremium: true,
  },
];

/** All users from batch 3 combined */
export const demoUsersBatch3 = [
  ...hebrewUsers,
  ...englishUsers,
  ...mixedUsers,
  ...additionalUsers,
];
