/**
 * Seed Data - User Definitions (Part 1)
 * Admin user + first 10 demo users
 */

import { Gender, Language } from '@prisma/client';

export const adminUser = {
  id: 'admin-user-1',
  email: 'admin@bellor.app',
  firstName: 'Admin',
  lastName: 'User',
  gender: Gender.MALE,
  preferredLanguage: Language.ENGLISH,
  bio: 'System administrator',
  birthDate: new Date('1990-01-01'),
  lookingFor: [Gender.FEMALE],
  profileImages: ['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400'],
  isAdmin: true,
  isVerified: true,
};

/** First batch of demo users (indices 0-9 in the final array) */
export const demoUsersBatch1 = [
  adminUser,
  {
    id: 'demo-user-1',
    email: 'demo_sarah_special@bellor.app',
    firstName: 'Sarah',
    lastName: 'Cohen',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Adventure seeker and coffee enthusiast. Love hiking and trying new cuisines!',
    birthDate: new Date('1995-03-15'),
    lookingFor: [Gender.MALE],
    profileImages: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400'],
  },
  {
    id: 'demo-user-2',
    email: 'demo_david_special@bellor.app',
    firstName: 'David',
    lastName: 'Levy',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Software engineer by day, guitarist by night. Always up for a spontaneous road trip!',
    birthDate: new Date('1992-07-22'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400'],
  },
  {
    id: 'demo-match-user-1-romantic',
    email: 'demo_maya@bellor.app',
    firstName: 'Demo_Maya',
    lastName: 'Levi',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'Creative soul who loves art and music. Looking for meaningful connections!',
    birthDate: new Date('1999-06-15'),
    lookingFor: [Gender.MALE],
    profileImages: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
      'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=400',
    ],
  },
  {
    id: 'demo-match-user-2-positive',
    email: 'demo_noam@bellor.app',
    firstName: 'Demo_Noam',
    lastName: 'Shapiro',
    gender: Gender.MALE,
    preferredLanguage: Language.HEBREW,
    bio: 'Tech enthusiast and nature lover. Always up for a hike!',
    birthDate: new Date('1996-03-22'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400'],
  },
  {
    id: 'demo-match-user-3-super',
    email: 'demo_shira@bellor.app',
    firstName: 'Demo_Shira',
    lastName: 'Katz',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'Dance is my language. Yoga, cooking, and good vibes!',
    birthDate: new Date('2001-09-08'),
    lookingFor: [Gender.MALE],
    profileImages: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400'],
  },
  {
    email: 'demo_sarah@bellor.app',
    firstName: 'Demo_Sarah',
    lastName: 'Johnson',
    gender: Gender.FEMALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Adventure seeker and coffee enthusiast. Love hiking and trying new cuisines!',
    birthDate: new Date('1995-03-15'),
    lookingFor: [Gender.MALE],
    profileImages: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
      'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=400',
    ],
  },
  {
    email: 'demo_michael@bellor.app',
    firstName: 'Demo_Michael',
    lastName: 'Chen',
    gender: Gender.MALE,
    preferredLanguage: Language.ENGLISH,
    bio: 'Software engineer by day, guitarist by night. Always up for a spontaneous road trip!',
    birthDate: new Date('1992-07-22'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400'],
  },
  {
    email: 'demo_yael@bellor.app',
    firstName: 'Demo_Yael',
    lastName: 'Cohen',
    gender: Gender.FEMALE,
    preferredLanguage: Language.HEBREW,
    bio: 'Creative soul, loves art, music and travel. Looking for someone to share new experiences!',
    birthDate: new Date('1996-11-08'),
    lookingFor: [Gender.MALE],
    profileImages: ['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400'],
  },
  {
    email: 'demo_david@bellor.app',
    firstName: 'Demo_David',
    lastName: 'Levi',
    gender: Gender.MALE,
    preferredLanguage: Language.HEBREW,
    bio: 'Software engineer, loves sports and hiking. Looking for a serious relationship.',
    birthDate: new Date('1990-05-12'),
    lookingFor: [Gender.FEMALE],
    profileImages: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400'],
  },
];
