export const faqs = [
  { id: 1, category: 'Getting Started', question: 'How do I create my profile?', answer: 'After signing up, complete the onboarding process which includes adding photos, answering questions about yourself, and setting your preferences. Make sure to complete all sections for the best matching results.' },
  { id: 2, category: 'Getting Started', question: 'What makes Bellor different from other dating apps?', answer: 'Bellor focuses on authentic connections through daily creative missions, video responses, and meaningful conversations. We prioritize quality matches over quantity, and our unique "Shared Space" lets you see how others express themselves.' },
  { id: 3, category: 'Matching', question: 'How does the matching algorithm work?', answer: 'Our algorithm considers your profile information, preferences, compatibility quiz answers, and engagement patterns. We also look at shared interests, values, and how you interact with daily missions.' },
  { id: 4, category: 'Matching', question: 'What is a Super Like?', answer: 'A Super Like is a special way to show someone you\'re really interested. It includes a personalized message and gives you priority visibility on their profile. Premium users get more Super Likes per day.' },
  { id: 5, category: 'Safety', question: 'How do I report inappropriate behavior?', answer: 'You can report users directly from their profile or messages. Go to Safety Center to submit detailed reports. All reports are reviewed by our team within 24 hours.' },
  { id: 6, category: 'Safety', question: 'How do I block someone?', answer: 'On any user\'s profile, tap the three dots menu and select "Block User". They won\'t be able to see your profile, message you, or appear in your discovery feed.' },
  { id: 7, category: 'Premium', question: 'What do I get with Premium?', answer: 'Premium includes unlimited likes, priority visibility, advanced filters, profile boosts, more Super Likes, read receipts, and access to premium-only events.' },
  { id: 8, category: 'Premium', question: 'Can I cancel my subscription?', answer: 'Yes, you can cancel anytime from Account Settings. You\'ll continue to have Premium benefits until the end of your billing period.' },
  { id: 9, category: 'Features', question: 'What are Daily Missions?', answer: 'Daily Missions are creative prompts that help you express yourself authentically. Complete them by responding with text, drawing, voice, or video. Your responses appear in the Shared Space feed.' },
  { id: 10, category: 'Features', question: 'How do Virtual Events work?', answer: 'Virtual Events are group video experiences like speed dating, mixers, and game nights. Register for upcoming events and receive a link before they start. It\'s a fun way to meet multiple people at once.' },
  { id: 11, category: 'Account', question: 'How do I delete my account?', answer: 'Go to Settings > Account Settings > Delete Account. This action is permanent and will remove all your data, matches, and messages.' },
  { id: 12, category: 'Account', question: 'Can I change my email address?', answer: 'Yes, go to Settings > Account Settings and update your email. You\'ll need to verify the new email address.' },
];
