#!/bin/bash
# ================================================
# Bellor MVP - Universal One-Command Installer
# ================================================
# Works on: Ubuntu, Debian, CentOS, macOS, WSL
# Usage: curl -fsSL https://raw.githubusercontent.com/your-org/Bellor_MVP/main/scripts/install-anywhere.sh | bash

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}"
cat << "EOF"
╔══════════════════════════════════════════════════════════╗
║                                                          ║
║         Bellor MVP - Universal Installer                ║
║         One Command to Rule Them All                    ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Detect OS
detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
        VER=$VERSION_ID
    elif [ -f /etc/redhat-release ]; then
        OS="centos"
    elif [ "$(uname)" == "Darwin" ]; then
        OS="macos"
    else
        OS="unknown"
    fi

    log_info "Detected OS: $OS"
}

# Install Docker
install_docker() {
    log_info "Installing Docker..."

    if command -v docker &> /dev/null; then
        log_info "Docker already installed: $(docker --version)"
        return 0
    fi

    case $OS in
        ubuntu|debian)
            curl -fsSL https://get.docker.com | sh
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER
            ;;
        centos|rhel|fedora)
            sudo yum install -y yum-utils
            sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
            sudo yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER
            ;;
        macos)
            log_warn "Please install Docker Desktop from: https://www.docker.com/products/docker-desktop"
            log_warn "Press Enter after installation..."
            read
            ;;
        *)
            log_error "Unsupported OS: $OS"
            log_info "Please install Docker manually: https://docs.docker.com/engine/install/"
            exit 1
            ;;
    esac

    log_info "Docker installed successfully!"
}

# Install Docker Compose
install_docker_compose() {
    log_info "Checking Docker Compose..."

    if docker compose version &> /dev/null; then
        log_info "Docker Compose already installed"
        return 0
    fi

    # Try legacy docker-compose
    if command -v docker-compose &> /dev/null; then
        log_info "Legacy docker-compose found"
        return 0
    fi

    log_info "Installing Docker Compose..."
    sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
}

# Generate secrets
generate_secrets() {
    log_info "Generating secure secrets..."

    JWT_SECRET=$(openssl rand -base64 32)
    JWT_REFRESH_SECRET=$(openssl rand -base64 32)
    POSTGRES_PASSWORD=$(openssl rand -base64 16)
    REDIS_PASSWORD=$(openssl rand -base64 16)

    log_info "Secrets generated!"
}

# Create .env file
create_env_file() {
    log_info "Creating environment file..."

    # Get domain or use localhost
    echo ""
    echo -e "${BLUE}Domain Configuration:${NC}"
    read -p "Enter your domain (or press Enter for localhost): " DOMAIN
    DOMAIN=${DOMAIN:-localhost}

    if [ "$DOMAIN" == "localhost" ]; then
        FRONTEND_URL="http://localhost"
        API_URL="http://localhost:3000"
        WS_URL="ws://localhost:3000"
        CDN_URL="http://localhost:3000"
    else
        FRONTEND_URL="https://$DOMAIN"
        API_URL="https://api.$DOMAIN"
        WS_URL="wss://api.$DOMAIN"
        CDN_URL="https://cdn.$DOMAIN"
    fi

    cat > .env.production << EOF
# Generated by Bellor Universal Installer
# Date: $(date)

# ======== Database ========
DATABASE_URL=postgresql://bellor:${POSTGRES_PASSWORD}@postgres:5432/bellor
POSTGRES_USER=bellor
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=bellor

# ======== Redis ========
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
REDIS_PASSWORD=${REDIS_PASSWORD}

# ======== JWT Secrets ========
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# ======== URLs ========
FRONTEND_URL=${FRONTEND_URL}
VITE_API_URL=${API_URL}
VITE_WS_URL=${WS_URL}
VITE_CDN_URL=${CDN_URL}

# ======== Storage (Optional - configure later) ========
# R2_ENDPOINT=https://xxx.r2.cloudflarestorage.com
# R2_ACCESS_KEY_ID=
# R2_SECRET_ACCESS_KEY=
# R2_BUCKET=bellor-media
# CDN_URL=${CDN_URL}

# ======== App Config ========
NODE_ENV=production
PORT=3000
HOST=0.0.0.0
LOG_LEVEL=info
EOF

    log_info ".env.production created!"
    log_warn "IMPORTANT: Keep this file secure!"
}

# Clone/Download project
setup_project() {
    log_info "Setting up project..."

    INSTALL_DIR="/opt/bellor"

    # Ask for installation directory
    echo ""
    read -p "Installation directory [${INSTALL_DIR}]: " USER_DIR
    INSTALL_DIR=${USER_DIR:-$INSTALL_DIR}

    # Check if git is available
    if command -v git &> /dev/null; then
        echo ""
        read -p "Git repository URL (or press Enter to skip): " REPO_URL

        if [ -n "$REPO_URL" ]; then
            log_info "Cloning from git..."
            sudo mkdir -p $(dirname $INSTALL_DIR)
            sudo git clone $REPO_URL $INSTALL_DIR
            cd $INSTALL_DIR
            return 0
        fi
    fi

    # Manual setup
    log_warn "Please copy your Bellor_MVP directory to: $INSTALL_DIR"
    log_warn "Then run: cd $INSTALL_DIR && ./scripts/install-anywhere.sh --continue"
    exit 0
}

# Deploy
deploy() {
    log_info "Deploying Bellor MVP..."

    # Build images
    log_info "Building Docker images (this may take 5-10 minutes)..."
    docker compose -f docker-compose.prod.yml build

    # Start services
    log_info "Starting services..."
    docker compose -f docker-compose.prod.yml --env-file .env.production up -d

    # Wait for services
    log_info "Waiting for services to be ready..."
    sleep 10

    # Run migrations
    log_info "Running database migrations..."
    docker compose -f docker-compose.prod.yml exec -T api sh -c "cd /app/apps/api && npx prisma migrate deploy" || true

    # Seed database
    log_info "Seeding database with demo data..."
    docker compose -f docker-compose.prod.yml exec -T api sh -c "cd /app/apps/api && npx prisma db seed" || true

    # Show status
    echo ""
    log_info "Deployment complete! 🎉"
    echo ""
    docker compose -f docker-compose.prod.yml ps
}

# Show final instructions
show_instructions() {
    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                                                          ║${NC}"
    echo -e "${GREEN}║         ✅ Bellor MVP Installed Successfully!            ║${NC}"
    echo -e "${GREEN}║                                                          ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
    echo ""

    if [ "$DOMAIN" == "localhost" ]; then
        echo -e "${BLUE}📱 Access your application:${NC}"
        echo -e "   Frontend: http://localhost"
        echo -e "   API:      http://localhost:3000"
        echo -e "   Health:   http://localhost:3000/health"
    else
        echo -e "${BLUE}📱 Access your application:${NC}"
        echo -e "   Frontend: https://${DOMAIN}"
        echo -e "   API:      https://api.${DOMAIN}"
        echo ""
        echo -e "${YELLOW}⚠️  Remember to:${NC}"
        echo -e "   1. Point your DNS to this server's IP"
        echo -e "   2. Setup SSL with: sudo certbot --nginx"
    fi

    echo ""
    echo -e "${BLUE}🔐 Demo Users (password: Demo123!):${NC}"
    echo -e "   - demo_sarah@bellor.app"
    echo -e "   - demo_yael@bellor.app"
    echo -e "   - demo_maria@bellor.app"
    echo ""
    echo -e "${BLUE}📊 Useful Commands:${NC}"
    echo -e "   View logs:    docker compose -f docker-compose.prod.yml logs -f"
    echo -e "   Stop:         docker compose -f docker-compose.prod.yml stop"
    echo -e "   Start:        docker compose -f docker-compose.prod.yml start"
    echo -e "   Restart:      docker compose -f docker-compose.prod.yml restart"
    echo -e "   Update:       git pull && docker compose -f docker-compose.prod.yml up -d --build"
    echo ""
    echo -e "${GREEN}🎉 Happy Coding!${NC}"
    echo ""
}

# Main installation flow
main() {
    log_info "Starting Bellor MVP installation..."
    echo ""

    # Check if running with --continue flag
    if [ "$1" == "--continue" ]; then
        log_info "Continuing installation..."
    else
        detect_os
        install_docker
        install_docker_compose
        generate_secrets
        create_env_file
        setup_project
    fi

    # Deploy
    deploy
    show_instructions

    log_info "Installation completed!"
}

# Run main
main "$@"
