# ================================================
# Bellor MVP - Windows One-Command Installer
# ================================================
# Usage: irm https://raw.githubusercontent.com/your-org/Bellor_MVP/main/scripts/install-anywhere.ps1 | iex

Write-Host @"
╔══════════════════════════════════════════════════════════╗
║                                                          ║
║         Bellor MVP - Windows Installer                  ║
║         One Command to Rule Them All                    ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
"@ -ForegroundColor Cyan

function Write-Info {
    param($Message)
    Write-Host "[INFO] $Message" -ForegroundColor Green
}

function Write-Warn {
    param($Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Write-Error {
    param($Message)
    Write-Host "[ERROR] $Message" -ForegroundColor Red
}

# Check if running as Administrator
function Test-Admin {
    $currentUser = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    return $currentUser.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-Admin)) {
    Write-Error "This script must be run as Administrator!"
    Write-Info "Right-click PowerShell and select 'Run as Administrator'"
    exit 1
}

# Check Docker Desktop
function Test-Docker {
    try {
        $dockerVersion = docker --version
        Write-Info "Docker found: $dockerVersion"
        return $true
    }
    catch {
        return $false
    }
}

if (-not (Test-Docker)) {
    Write-Warn "Docker Desktop not found!"
    Write-Info "Installing Docker Desktop..."
    Write-Info "Please download and install from: https://www.docker.com/products/docker-desktop"
    Write-Info "After installation, restart this script."
    Start-Process "https://www.docker.com/products/docker-desktop"
    exit 0
}

# Generate secrets
function New-Secret {
    param($Length = 32)
    $bytes = New-Object byte[] $Length
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    return [Convert]::ToBase64String($bytes)
}

Write-Info "Generating secure secrets..."
$JWT_SECRET = New-Secret
$JWT_REFRESH_SECRET = New-Secret
$POSTGRES_PASSWORD = New-Secret -Length 16
$REDIS_PASSWORD = New-Secret -Length 16

# Get domain
Write-Host ""
Write-Host "Domain Configuration:" -ForegroundColor Cyan
$DOMAIN = Read-Host "Enter your domain (or press Enter for localhost)"
if ([string]::IsNullOrWhiteSpace($DOMAIN)) {
    $DOMAIN = "localhost"
}

if ($DOMAIN -eq "localhost") {
    $FRONTEND_URL = "http://localhost"
    $API_URL = "http://localhost:3000"
    $WS_URL = "ws://localhost:3000"
    $CDN_URL = "http://localhost:3000"
} else {
    $FRONTEND_URL = "https://$DOMAIN"
    $API_URL = "https://api.$DOMAIN"
    $WS_URL = "wss://api.$DOMAIN"
    $CDN_URL = "https://cdn.$DOMAIN"
}

# Get installation directory
$INSTALL_DIR = Read-Host "Installation directory (press Enter for C:\Bellor)"
if ([string]::IsNullOrWhiteSpace($INSTALL_DIR)) {
    $INSTALL_DIR = "C:\Bellor"
}

# Create directory
if (-not (Test-Path $INSTALL_DIR)) {
    Write-Info "Creating directory: $INSTALL_DIR"
    New-Item -ItemType Directory -Path $INSTALL_DIR -Force | Out-Null
}

Set-Location $INSTALL_DIR

# Clone or prompt for files
$REPO_URL = Read-Host "Git repository URL (or press Enter to skip)"
if (-not [string]::IsNullOrWhiteSpace($REPO_URL)) {
    Write-Info "Cloning from git..."
    git clone $REPO_URL .
} else {
    Write-Warn "Please copy your Bellor_MVP files to: $INSTALL_DIR"
    Write-Info "Press Enter when ready..."
    Read-Host
}

# Create .env file
Write-Info "Creating .env.production file..."
$envContent = @"
# Generated by Bellor Windows Installer
# Date: $(Get-Date)

# ======== Database ========
DATABASE_URL=postgresql://bellor:${POSTGRES_PASSWORD}@postgres:5432/bellor
POSTGRES_USER=bellor
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=bellor

# ======== Redis ========
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
REDIS_PASSWORD=${REDIS_PASSWORD}

# ======== JWT Secrets ========
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# ======== URLs ========
FRONTEND_URL=${FRONTEND_URL}
VITE_API_URL=${API_URL}
VITE_WS_URL=${WS_URL}
VITE_CDN_URL=${CDN_URL}

# ======== App Config ========
NODE_ENV=production
PORT=3000
HOST=0.0.0.0
LOG_LEVEL=info
"@

$envContent | Out-File -FilePath ".env.production" -Encoding UTF8

# Deploy
Write-Info "Building Docker images (this may take 5-10 minutes)..."
docker compose -f docker-compose.prod.yml build

Write-Info "Starting services..."
docker compose -f docker-compose.prod.yml --env-file .env.production up -d

Write-Info "Waiting for services..."
Start-Sleep -Seconds 10

Write-Info "Running database migrations..."
docker compose -f docker-compose.prod.yml exec -T api sh -c "cd /app/apps/api && npx prisma migrate deploy"

Write-Info "Seeding database..."
docker compose -f docker-compose.prod.yml exec -T api sh -c "cd /app/apps/api && npx prisma db seed"

# Show results
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║         ✅ Bellor MVP Installed Successfully!            ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""

Write-Host "📱 Access your application:" -ForegroundColor Cyan
Write-Host "   Frontend: $FRONTEND_URL"
Write-Host "   API:      $API_URL"
Write-Host "   Health:   $API_URL/health"
Write-Host ""

Write-Host "🔐 Demo Users (password: Demo123!):" -ForegroundColor Cyan
Write-Host "   - demo_sarah@bellor.app"
Write-Host "   - demo_yael@bellor.app"
Write-Host ""

Write-Host "📊 Useful Commands:" -ForegroundColor Cyan
Write-Host "   View logs:    docker compose -f docker-compose.prod.yml logs -f"
Write-Host "   Stop:         docker compose -f docker-compose.prod.yml stop"
Write-Host "   Start:        docker compose -f docker-compose.prod.yml start"
Write-Host ""

Write-Host "🎉 Installation complete!" -ForegroundColor Green
